name: Snyk security scan

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Triggers scan-pr flow for every opened/updated pull request
    branches:
    - main
    - add-ci-security-scan
  push:  # Triggers scan-repo flow for every push to the specified branches
    branches:
    - main
    - add-ci-security-scan
  workflow_dispatch:  # The repository will be scanned on demand

jobs:
  security:
    uses: Istari-digital/istari-ci/.github/workflows/snyk-security-scan-python.yml@main
    secrets: inherit